[package]
name = "thledbar"
version = "1.2.2"
edition = "2021"

[dependencies]
cnx = { git = "https://github.com/thled/cnx", branch = "fix-cpu-usage" }
cnx-contrib = { git = "https://github.com/thled/cnx", branch = "fix-cpu-usage" }
anyhow = "1.0.62"
xrdb = "0.1.1"
