[package]
name = "thledbar"
version = "1.1.2"
edition = "2021"

[dependencies]
cnx = { git = "https://github.com/thled/cnx", branch = "color_from_hex" }
cnx-contrib = { git = "https://github.com/thled/cnx", branch = "color_from_hex" }
anyhow = "1.0.62"
xrdb = "0.1.1"
