[package]
name = "thledbar"
version = "1.0.0"
edition = "2021"

[dependencies]
cnx = { git = "https://github.com/thled/cnx" }
cnx-contrib = { git = "https://github.com/thled/cnx" }
anyhow = "1.0.62"
xrdb = "0.1.1"
