on: [push]

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Run check
        uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test

  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          component: rustfmt
      - name: Run fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt --all -- --check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          component: clippy
      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy -- -D warnings

  build:
    name: Build binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build --all --release
      - run: strip target/release/thledbar
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: app/target/release/thledbar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

